### ISSUE TITLE
Search Engines no longer support pinging with new sitemaps.

### ISSUE THREAD

**Issue by torvista** [lat9/sitemapxml#26]
Google responds ok, Bing no.
![2023-10-15 20_00_51-SiteMapXML (3 9 9)](https://github.com/lat9/sitemapxml/assets/4391026/241b5414-b0e6-4d0b-a320-7aa6b46faab8)

**Comment by lat9** [comment]
And Google is deprecating its Ping as well: https://developers.google.com/search/blog/2023/06/sitemaps-lastmod-ping

I'll just get that ping portion outta there.
